<?php

namespace DoctrineProxies\__CG__\App\Models\Market;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CommissionCompensation extends \App\Models\Market\CommissionCompensation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'rate', 'rate_type', 'conversion_type', 'average_order_value', 'affiliate_network', 'affiliate_program_name', 'affiliate_links', 'id'];
        }

        return ['__isInitialized__', 'rate', 'rate_type', 'conversion_type', 'average_order_value', 'affiliate_network', 'affiliate_program_name', 'affiliate_links', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CommissionCompensation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRate', []);

        return parent::getRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRate($rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRate', [$rate]);

        return parent::setRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRateType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateType', []);

        return parent::getRateType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateType($rate_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateType', [$rate_type]);

        return parent::setRateType($rate_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getConversionType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConversionType', []);

        return parent::getConversionType();
    }

    /**
     * {@inheritDoc}
     */
    public function setConversionType($conversion_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConversionType', [$conversion_type]);

        return parent::setConversionType($conversion_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageOrderValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageOrderValue', []);

        return parent::getAverageOrderValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setAverageOrderValue($average_order_value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAverageOrderValue', [$average_order_value]);

        return parent::setAverageOrderValue($average_order_value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateNetwork', []);

        return parent::getAffiliateNetwork();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateNetwork($affiliate_network)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateNetwork', [$affiliate_network]);

        return parent::setAffiliateNetwork($affiliate_network);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateProgramName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateProgramName', []);

        return parent::getAffiliateProgramName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateProgramName($affiliate_program_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateProgramName', [$affiliate_program_name]);

        return parent::setAffiliateProgramName($affiliate_program_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateLinks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateLinks', []);

        return parent::getAffiliateLinks();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateLinks($affiliate_links)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateLinks', [$affiliate_links]);

        return parent::setAffiliateLinks($affiliate_links);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
